using Hickory.Api.Features.KnowledgeBase.Models;
using Hickory.Api.Infrastructure.Data.Entities;
using NpgsqlTypes;

namespace Hickory.Api.Features.KnowledgeBase;

/// <summary>
/// Shared helper methods for knowledge article operations
/// </summary>
public static class KnowledgeArticleHelpers
{
    /// <summary>
    /// Generates a PostgreSQL full-text search vector from article title and content.
    /// 
    /// NOTE: As of EF Core 9.0, SearchVector is now a computed column in the database.
    /// This method is deprecated and should not be used. The search vector is automatically
    /// generated by PostgreSQL using:
    /// setweight(to_tsvector('english', title), 'A') || setweight(to_tsvector('english', content), 'B')
    /// 
    /// Title is weighted 'A' (highest) for better search relevance, content is weighted 'B'.
    /// </summary>
    /// <param name="title">Article title (not used - provided for compatibility)</param>
    /// <param name="content">Article content (not used - provided for compatibility)</param>
    /// <returns>Always returns null as SearchVector is now database-computed</returns>
    [Obsolete("SearchVector is now a computed column. Remove calls to this method.")]
    public static NpgsqlTsVector? GenerateSearchVector(string title, string content)
    {
        // SearchVector is now computed by the database, not set manually
        // See KnowledgeArticleConfiguration for the computed column definition
        return null;
    }

    /// <summary>
    /// Maps a KnowledgeArticle entity to a complete ArticleDto
    /// </summary>
    public static ArticleDto MapToDto(KnowledgeArticle article)
    {
        return new ArticleDto
        {
            Id = article.Id,
            Title = article.Title,
            Content = article.Content,
            Status = article.Status.ToString(),
            CategoryId = article.CategoryId,
            CategoryName = article.Category?.Name,
            Tags = article.Tags.Select(t => t.Name).ToList(),
            ViewCount = article.ViewCount,
            HelpfulCount = article.HelpfulCount,
            NotHelpfulCount = article.NotHelpfulCount,
            AuthorId = article.AuthorId,
            AuthorName = $"{article.Author.FirstName} {article.Author.LastName}",
            LastUpdatedById = article.LastUpdatedById,
            LastUpdatedByName = article.LastUpdatedBy != null 
                ? $"{article.LastUpdatedBy.FirstName} {article.LastUpdatedBy.LastName}" 
                : null,
            CreatedAt = article.CreatedAt,
            UpdatedAt = article.UpdatedAt,
            PublishedAt = article.PublishedAt
        };
    }

    /// <summary>
    /// Maps a KnowledgeArticle entity to a simplified ArticleListItemDto for list views
    /// </summary>
    public static ArticleListItemDto MapToListItemDto(KnowledgeArticle article)
    {
        return new ArticleListItemDto
        {
            Id = article.Id,
            Title = article.Title,
            Status = article.Status.ToString(),
            CategoryId = article.CategoryId,
            CategoryName = article.Category?.Name,
            Tags = article.Tags.Select(t => t.Name).ToList(),
            ViewCount = article.ViewCount,
            HelpfulCount = article.HelpfulCount,
            AuthorName = $"{article.Author.FirstName} {article.Author.LastName}",
            CreatedAt = article.CreatedAt,
            PublishedAt = article.PublishedAt
        };
    }
}
