version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hickory-postgres
    environment:
      POSTGRES_USER: hickory
      POSTGRES_PASSWORD: hickory_dev_password
      POSTGRES_DB: hickory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hickory"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: hickory-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    container_name: hickory-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=hickory;Username=hickory;Password=hickory_dev_password
      - ConnectionStrings__Redis=redis:6379
      - JWT__Secret=your-super-secret-jwt-key-change-this-in-production
      - JWT__Issuer=hickory-api
      - JWT__Audience=hickory-web
      - JWT__ExpirationMinutes=60
      - Logging__LogLevel__Default=Information
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web:
    build:
      context: ..
      dockerfile: docker/web.Dockerfile
    container_name: hickory-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api/v1
      - NEXT_PUBLIC_WS_URL=ws://localhost:5000
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
  redis_data:
