version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
    command: sleep infinity
    network_mode: service:db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=localhost;Port=5432;Database=hickory;Username=hickory;Password=hickory_dev_password
      - ConnectionStrings__Redis=localhost:6379
      - JWT__Secret=your-super-secret-jwt-key-change-this-in-production-min-32-chars
      - JWT__Issuer=hickory-api
      - JWT__Audience=hickory-web
      - JWT__ExpirationMinutes=60
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXT_PUBLIC_WS_URL=ws://localhost:5000

  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hickory
      POSTGRES_PASSWORD: hickory_dev_password
      POSTGRES_DB: hickory
    ports:
      - "5432:5432"
      - "5000:5000"   # API
      - "3000:3000"   # Web
      - "6379:6379"   # Redis
      - "8025:8025"   # MailHog UI
      - "1025:1025"   # MailHog SMTP

  # Redis Cache
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    network_mode: service:db

  # MailHog - Email testing
  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    network_mode: service:db

volumes:
  postgres-data:
  redis-data:
