name: Quick Tests

# Run only unit tests for fast feedback
# Triggered on every push to feature branches

on:
  push:
    branches: ['feature/**', 'fix/**']

jobs:
  quick-test:
    name: Quick Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci

      - name: Run .NET Tests
        run: dotnet test apps/api/Hickory.Api.Tests/Hickory.Api.Tests.csproj --verbosity minimal

      - name: Run Web Tests
        run: npx nx test web --ci

      - name: Run CLI Tests
        run: npx nx test cli --ci

      - name: Test Summary
        if: always()
        run: |
          echo "✅ Quick tests completed!"
          echo "- .NET API: .NET unit tests"
          echo "- Web: Jest unit tests"
          echo "- CLI: Jest unit tests"
